services:
  - type: web
    name: hrms-back
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: switchyard.proxy.rlwy.net
      - key: DB_PORT
        value: 17148
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: AwtfFxdSspLgKcglXppogyxeGyUGNuAX
