services:
  - type: web
    name: hrms-back
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-noursayf7.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: noursayf7_hrms
      - key: DB_USERNAME
        value: noursayf7
      - key: DB_PASSWORD
        value: Noursayf@nour.com
